# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations
from django.db.models import Q # Import Q for potential future complex queries

# Define the function to update the data
def set_default_user_type(apps, schema_editor):
    # We need to get the historical version of the User model
    # It's important to use apps.get_model instead of direct import
    # to work with the model version at this point in migration history.
    User = apps.get_model('users', 'User') # Replace 'users' if your app name is different
    db_alias = schema_editor.connection.alias

    print("\n  Updating users with empty user_type...") # Optional: Add print for feedback

    # Find users where user_type is an empty string
    # Filter using the specific value causing the error
    users_to_update = User.objects.using(db_alias).filter(user_type='')

    updated_count = 0
    for user in users_to_update:
        user.user_type = 'rider' # Set to your desired default
        user.save(update_fields=['user_type'])
        updated_count += 1

    if updated_count:
        print(f"  Updated {updated_count} user(s) to default user_type 'rider'.")
    else:
        print("  No users found with empty user_type to update.")

# Define a function for reversing the migration (optional, but good practice)
# In this case, reversing doesn't make much sense as we are fixing bad data.
# Setting it back to '' would reintroduce the error. So we use migrations.RunPython.noop.
def reverse_set_default_user_type(apps, schema_editor):
    # This operation is correcting bad data to a valid default.
    # Reversing it isn't practical or desirable.
    print("\n  Skipping reverse operation for fix_empty_user_type (no practical reverse action).")
    pass # Or explicitly raise IrreversibleError if preferred

class Migration(migrations.Migration):

    # Add dependency on the migration that created the user_type field,
    # or the last migration in the 'users' app if unsure.
    # Replace '000Y_previous_migration' with the actual previous migration name.
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_user_type, reverse_code=reverse_set_default_user_type),
        # Use migrations.RunPython.noop as the reverse if you don't want a reverse function:
        # migrations.RunPython(set_default_user_type, reverse_code=migrations.RunPython.noop),
    ]