# Generated by Django 5.1.7 on 2025-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_update_userverification_with_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ghana_card_image",
            field=models.ImageField(blank=True, null=True, upload_to="ghana_cards/"),
        ),
        migrations.AddField(
            model_name="user",
            name="ghana_card_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
