# Generated by Django 5.2.1 on 2025-07-07 01:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Current GPS location (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
    ]
