# Generated by Django 5.1.7 on 2025-05-06 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ride",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "Ride",
                "verbose_name_plural": "Rides",
            },
        ),
        migrations.AlterModelOptions(
            name="riderating",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ride Rating",
                "verbose_name_plural": "Ride Ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="savedlocation",
            options={
                "ordering": ["location_type", "name"],
                "verbose_name": "Saved Location",
                "verbose_name_plural": "Saved Locations",
            },
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="started_at",
            new_name="arrived_at_pickup_at",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="distance",
            new_name="distance_km",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="created_at",
            new_name="requested_at",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="savedlocation",
            name="location",
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_address",
            field=models.TextField(
                blank=True,
                help_text="Textual address or description of destination",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_lat",
            field=models.DecimalField(
                decimal_places=7,
                default=0.0,
                help_text="Latitude of destination",
                max_digits=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_lng",
            field=models.DecimalField(
                decimal_places=7,
                default=0.0,
                help_text="Longitude of destination",
                max_digits=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="duration_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="estimated_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_address",
            field=models.TextField(
                blank=True,
                help_text="Textual address or description of pickup",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_location_lat",
            field=models.DecimalField(
                decimal_places=7,
                default=0.0,
                help_text="Latitude of pickup location",
                max_digits=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_location_lng",
            field=models.DecimalField(
                decimal_places=7,
                default=0.0,
                help_text="Longitude of pickup location",
                max_digits=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="trip_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderating",
            name="rated_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="riderating",
            name="rater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="latitude",
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="longitude",
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="base_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="distance_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "driver"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "rider"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("ACCEPTED", "Accepted"),
                    ("ON_ROUTE_TO_PICKUP", "On Route to Pickup"),
                    ("ARRIVED_AT_PICKUP", "Arrived at Pickup"),
                    ("ON_TRIP", "On Trip"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED_BY_RIDER", "Cancelled by Rider"),
                    ("CANCELLED_BY_DRIVER", "Cancelled by Driver"),
                    ("NO_DRIVER_FOUND", "No Driver Found"),
                ],
                db_index=True,
                default="REQUESTED",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="total_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="riderating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="savedlocation",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedlocation",
            name="location_type",
            field=models.CharField(
                choices=[("HOME", "Home"), ("WORK", "Work"), ("OTHER", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="savedlocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_location_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riderating",
            unique_together={("ride", "rater")},
        ),
        migrations.DeleteModel(
            name="RideLocation",
        ),
    ]
