# Generated by Django 5.2.1 on 2025-07-11 01:42

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


def populate_ride_points(apps, schema_editor):
    Ride = apps.get_model('rides', 'Ride')
    for ride in Ride.objects.all():
        if ride.pickup_location_lat is not None and ride.pickup_location_lng is not None:
            ride.pickup_location = Point(float(ride.pickup_location_lng), float(ride.pickup_location_lat), srid=4326)
        if ride.destination_lat is not None and ride.destination_lng is not None:
            ride.destination = Point(float(ride.destination_lng), float(ride.destination_lat), srid=4326)
        ride.save(update_fields=['pickup_location', 'destination'])

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_driveravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="destination",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Destination as Point (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Pickup location as Point (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.RunPython(populate_ride_points, noop),
    ]
